import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.scss'

import Header from '@/components/Header/Header'
import Introduce from '@/sections/Introduce/Introduce'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>

        <Introduce />

      </main>
    </div>
  )
}

export default Home
